name: Manual Trigger

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Your name'
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "HELLO ${{ github.event.inputs.username }}"
