name: 'NuGet Composite Action'
description: 'Handles NuGet commands, installation, and restore in a single action'
inputs:
  taskType:
    description: 'Type of NuGet task to run (command, installer, restore)'
    required: false
  command:
    description: 'NuGet command (required for NuGet@0)'
    required: false
  solution:
    description: 'Path to solution or packages.config'
    required: true
    default: '**/*.sln'
  restoreMode:
    description: 'Restore or install mode (required for NuGetInstaller@0)'
    required: false
    default: 'restore'
  nugetConfigPath:
    description: 'Path to NuGet.config'
    required: false
  verbosity:
    description: 'Verbosity level'
    required: false
    default: 'Normal'
  nuGetVersion:
    description: 'NuGet version to use (e.g., 3.3.0, 3.5.0.1829, 4.0.0.2283, or custom)'
    required: false
    default: '3.3.0'
  selectOrConfig:
    description: 'Feeds to use (select or config)'
    required: false
    default: 'select'

runs:
  using: "composite"
  steps:
    - name: Run NuGet Command (NuGet@0)
      if: ${{ inputs.taskType == 'command' && inputs.command }}
      run: |
        nuget ${{ inputs.command }} ${{ inputs.arguments }}
      shell: pwsh

    - name: Run NuGet Installer (NuGetInstaller@0)
      if: ${{ inputs.taskType == 'installer' }}
      run: |
        nuget restore ${{ inputs.solution }} 
          --config-file ${{ inputs.nugetConfigPath }} 
          --verbosity ${{ inputs.verbosity }}
          --version ${{ inputs.nuGetVersion }}
      shell: pwsh

    - name: Run NuGet Restore (NuGetRestore@1)
      if: ${{ inputs.taskType == 'restore' }}
      run: |
        nuget restore ${{ inputs.solution }} 
          --config-file ${{ inputs.nugetConfigPath }} 
          --verbosity ${{ inputs.verbosity }}
          --select-or-config ${{ inputs.selectOrConfig }}
      shell: pwsh
