name: Call VSBuild .NET Solution with VSBuild Reusable Template 71a9a2d3-a98a-4caa-96ab-affca411ecda
##

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Composite Action for Build
        uses: ./.github/actions/vsbuild-composite-action
        with:
          solution: "AspnetCoreMvcFull.sln"
          configuration: "Release"
          platform: "Any CPU"
          msbuildArgs: "/p:Optimize=true"
          restoreNugetPackages: true
