name: Call VSBuild .NET Solution with VSBuild Reusable Template 71a9a2d3-a98a-4caa-96ab-affca411ecda
##

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  VSbuild-Template:
    uses: ./.github/workflows/test-vsbuild-workflow.yml
    #uses: ./.github/workflows/template_VSBuild-VSTEST_71a9a2d3-a98a-4caa-96ab-affca411ecda.yml

    with:
      runsOn: "self-hosted" #"windows-latest"
      solution: "*/*.sln"
      vsVersion: "latest"
      msbuildArgs: "/p:Optimize=true"
      platform: "Any CPU"
      configuration: "Release"
      clean: true
      maximumCpuCount: true
      restoreNugetPackages: true
      msbuildArchitecture: "x86"
      logProjectEvents: true
      createLogFile: true
      logFileVerbosity: "normal"
      enableDefaultLogger: true
      customVersion: "1.0.0"
