name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'test'

jobs:
  manual: 
    runs-on: windows-latest

    steps:
     - name: Greetings
       run: echo "${{ inputs.name }}"
