name: Manual workflow

on:
  repository_dispatch:
    types: [trigger-manual]
    inputs:
      name:
        description: 'Name'
        type: string
        required: true

jobs:
  manual: 
    runs-on: windows-latest

    steps:
     - name: Greetings
       run: echo "Hello ${{ github.event.client_payload.username }}"
